default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 1695
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: apiGames_development

test:
  <<: *default
  database: apiGames_test

production:
  <<: *default
  database: apiGames_production
  username: postgres
  password: 1695
